// $ANTLR 2.7.7 (2006-11-01): "Parser.g" -> "DecafParser.java"$

  	package decaf;
  	import decaf.ir.ast.*;
  	import java.util.List;
  	import java.util.ArrayList;

public interface DecafParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int TK_class = 4;
	int TK_if = 5;
	int TK_else = 6;
	int TK_for = 7;
	int TK_return = 8;
	int TK_break = 9;
	int TK_continue = 10;
	int TK_callout = 11;
	int TK_true = 12;
	int TK_false = 13;
	int TK_int = 14;
	int TK_boolean = 15;
	int TK_void = 16;
	int LCURLY = 17;
	int RCURLY = 18;
	int LPAREN = 19;
	int RPAREN = 20;
	int LSQUARE = 21;
	int RSQUARE = 22;
	int WS_ = 23;
	int SL_COMMENT = 24;
	int STRING = 25;
	int CHAR = 26;
	int COMMA = 27;
	int SEMI = 28;
	int PLUS = 29;
	int MINUS = 30;
	int MULDIV = 31;
	int MOD = 32;
	int ASSIGNPLUSEQ = 33;
	int ASSIGNMINUSEQ = 34;
	int ASSIGNEQ = 35;
	int LESS = 36;
	int MORE = 37;
	int LEQ = 38;
	int GEQ = 39;
	int CEQ = 40;
	int NEQ = 41;
	int AND = 42;
	int OR = 43;
	int NOT = 44;
	int ID = 45;
	int INTLIT = 46;
	int ESC = 47;
	int VALIDCHARS = 48;
	int ALPHA = 49;
	int DIGIT = 50;
	int HEX_DIGIT = 51;
	int ALPHA_NUM = 52;
	int DECIMAL = 53;
	int HEX = 54;
}
