// $ANTLR 2.7.7 (2006-11-01): "Parser.g" -> "DecafParser.java"$

  package decaf;
  import ir.ast.*;
  import java.util.List;
  import java.util.ArrayList;

public interface DecafParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int TK_class = 4;
	int TK_if = 5;
	int TK_else = 6;
	int TK_for = 7;
	int TK_return = 8;
	int TK_break = 9;
	int TK_continue = 10;
	int TK_callout = 11;
	int TK_true = 12;
	int TK_false = 13;
	int TK_int = 14;
	int TK_boolean = 15;
	int TK_void = 16;
	int TK_Program = 17;
	int LCURLY = 18;
	int RCURLY = 19;
	int LPAREN = 20;
	int RPAREN = 21;
	int LSQUARE = 22;
	int RSQUARE = 23;
	int WS_ = 24;
	int SL_COMMENT = 25;
	int STRING = 26;
	int CHAR = 27;
	int COMMA = 28;
	int SEMI = 29;
	int PLUS = 30;
	int MINUS = 31;
	int MULDIV = 32;
	int MOD = 33;
	int ASSIGNPLUSEQ = 34;
	int ASSIGNMINUSEQ = 35;
	int ASSIGNEQ = 36;
	int LESS = 37;
	int MORE = 38;
	int LEQ = 39;
	int GEQ = 40;
	int CEQ = 41;
	int NEQ = 42;
	int AND = 43;
	int OR = 44;
	int NOT = 45;
	int ID = 46;
	int INTLIT = 47;
	int ESC = 48;
	int VALIDCHARS = 49;
	int ALPHA = 50;
	int DIGIT = 51;
	int HEX_DIGIT = 52;
	int ALPHA_NUM = 53;
	int DECIMAL = 54;
	int HEX = 55;
	int ASSIGNPLUSNEQ = 56;
}
